name: mineheight
version: '${project.version}'
main: blue.lhf.mineheight.MineHeight
api-version: '1.21'
authors: [bluelhf]
description: Realistic height in Minecraft

permissions:
    mineheight.height:
        description: Allows players to set their in-game height
        default: true

    mineheight.height.others:
        description: Allows players to set other players' in-game height
        default: op